### ISSUE TITLE
parser upload error help needed

### ISSUE THREAD

**Issue by nb950** [QASymphony/pulse-community#11]
I made some progress , but stuck at uploading testcase to qtest using pulse 9.x 

output of parser formattedResults :

testcase {
  status: 'PASS',
  name: 'run xxxx',
  attachments: [],
  exe_start_date: '2020-06-10T21:13:32.779Z',
  exe_end_date: '2020-06-10T21:13:33.325Z',
  automation_content: '1',
  module_names: [ '1488' ]
}

STD ERROR :

(node:28408) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:28408) UnhandledPromiseRejectionWarning: #<Body>
(node:28408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

In the UpdateQTestWithFormattedResults :

I used the bearer token for valid user
is the HTTPS URL correct , the github has HTTP in the code ?

var standardHearders = {
        'Content-Type': 'application/json',
        'Authorization': `bearer ${'xxxxxxxxxxx'}`
    }

    var createLogsAndTCs = function () {
        console.log("About to call post")
        var opts = {
            url: "https://xxxx.yyy.com" + "/api/v3/projects/" + projectId + "/auto-test-logs?type=automation",

assuming this warning is from this pulse action is this error from POST call ?
any tip on how to troubleshoot this ?

**Comment by qaschris** [comment]
> assuming this warning is from this pulse action is this error from POST call ?
> any tip on how to troubleshoot this ?

Apologies, notifications weren't turned on.  I believe this issue was handled via Tricentis support, is that correct?

**Comment by qaschris** [comment]
Issue closed due to age - anyone with similar issues please open a support ticket with Tricentis in order to receive expedient assistance.
