### ISSUE TITLE
Enhancement: GZip compression for Pulse payloads

### ISSUE THREAD

**Issue by qaschris** [QASymphony/pulse-community#7]
Base64 encoding (and potentially encryption in a future enchancement) causes the payload size to become larger.  As the payload size for Pulse is currently limited, we should compress the payloads delivered to Pulse parser rules.

**Comment by 03-triple-threat** [comment]
@qaschris was a solution for this ever created? We are seeing our payloads hit limit for requests

**Comment by qaschris** [comment]
Sorry, it was not - we do not have packages on the Pulse backend to deflate compressed payloads.  If I can have the dev team add these modules to the Pulse package, we can revisit this in the future.
